@include('delivery.includes.head')
@include('delivery.includes.navbar')
@include('delivery.includes.header')
@include('delivery.includes.messages')
@yield('content')
@include('delivery.includes.footer')
